---
title: "My english activity log"
author:
  - name: Mussoi Lisa
date: 10-16-2019
output:
  distill::distill_article:
    self_contained: false
---
Let me to talk about me, I study biology at Umons during the week and I work in a hotel restaurant during the weekend. I have a kot so and I like to party so sometimes I go to the pub and I like talk to people even if they don't speak french. I play a lot of music, so everyday I think I play songs in english and I like to kwon the signification of the song saw I go to see teh lyrics in french and I learn a lot of new words. I like to travel with my friends too, so I must to speak english with people if I want to survive. But let me tell you more

*Travels...*
# September 2018
My first travel with my friends was in Dublin after my frist year at university. We went 5 days in a auberge, we were 3 so we must to speak english for the auberge at the airport or at restaurant. My friend are better than me in english but the don't like to speak so it was me who must talk to reserve the restaurant for exemple. And one day I went with my bestfriend in a music's store at Dublin and we ask to the seller to try somes guitar and he became to talk with us about music, the store etc It was very cool. 

# July 2019
I went with my bestfriend 2 weeks in a hotel in Turkey. I though that i could relax myself but when we arrive I realised that the only people who speak french in the hotel was my bestfriend. So the first day I speak with barman to ordered drink but we usually played dart so we met animator of the hotel and Irish people. The Irish people ask us if we want to played cart with them so we passed the evening with us and speak engish all the time and they have an awful accent...During this travel we met a danish girl too always speak in english. And during the end of our holiday we met holland people and we usually went to discotheque with them and they were speaking very well english and it's better than dutch for us. 

# September 2019
I went to Copenhagen with the same three friends and nobody speak danish so we must to talk english with everybody. 

*University*
I have english class every week and every two weeks I must to make a new article about my subject so every week I must to study my vocabulary, review my grammar and write on my blog. 

*Work*
Every weeks, I work in a hotel restaurant so I have a lot of foreign people since I don't speak russian, dutch or german I speak english everybody. For exemple one day an english man spode and laught with me during an hour. During summer a russian man was in belgium for 2 days and he told me that he make an europe trip with his car I found that so coool ! And I have a lot of collegue who don't speak english so they ask me to go to speak with they customer because they don't understand. 

*Party* 

# 10/10/19
I went to the pub and I saw a guys who are in my classroom it's erasmus who came from Catalogna so he speak only in english and I spoke a long time with him. 

# 11/15/19
Yesterday, I went to the pub and I met one turkish erasmus, and talk with her dans she told me that I speak well for a people who learn english. Maybe the beer help....

# 01/24/20
A friend made a party for the end of exam and the guys who came from catalogna was there and it was his last day in belgium so we spent all the party with him so we talked english all evening. 











