---
title: "Article 1 : Humans may be accidentally Geoengineering the Ocean"
author:
  - name: Mussoi Lisa
date: 10-16-2019
categories:
  - Ocean
  - Iron 
  - plankton 
preview: Image/plancton.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Vocabulary

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| field-based | carried out in nature |
| surface slicks | the water at the surface  | 
| targeted | aiming at for a attack |
| swordfish  | large fish with long jaw  |
| Toxin-laden  | with a lot of toxin |
| gut  | belly |
| scaling up |  elargement|


## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  |  Dr. Jonathan Whitney, it's a marin ecologist form the Joint Institute for Marine and Atmospheric Research and NOAA.|
| Published in?                |  11 November 2019                                                     |
| General topic?               |  the contamination of plastic in the larval fish                      |
| Procedure/what was examinated? | Near Hawaï some scientis observe that there are more larval fish at the surface slicks. It's was very nice beacause the laval fish developpe with phytoplakton and it's very good for the marin's ecosysteme.  In laval fish the plastic it's harmful but in adult fish it can cause stomach hurt and kill them.|
| Conclusions/discovery?       |  The surface slicks is the place where larval fish find a lot of food buut it's also the place where there are a lot of plastic so it eat a lot of minute particule of plasitc. The scientific find that a lot of species of fish are concerned by this probleme.  In laval fish the plastic it's harmful but in adult fish it can cause stomach hurt and kill them.       |
| Remaining questions?         | Today the scientific doesn't kown all the effect of the plastic on fishes.  |







