---
title: "Article 6 : Harbor porpoise calves exposed to neurotoxic PCBs in mothers' milk"
author:
  - name: Mussoi Lisa
date: 02-12-2020
categories: article-6_files/Images/beluga.jpg
  - PCB
  - Whales
  - Toxic
preview: 
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```










## Vocabulary 

| Words from the text | Synonym/explanation in English |
| ------------------- | ------------------------------ |
| Porpoise | Type of ceatacean |
| Run-off | Flow from|
| Dreging | Digging up of riverbed |
| Odontocetes | Familly of whales with theet |
| Understanding | Kwonledge |
| Orcas | Another type of cetacean, more precisely from the familly of odontocetes |
| Liguing | That lingers |
| Pathway | Little way  |
| PCB | Subtances toxic who are synthesize by industries |



## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  |Rosie Williams, she's a researcher at the Institute of Zoology and Brunel University London. Susan Jobling is a co-author at  Brunel University London's|
| Published in?                |  Decembre 2, 2019|
| General topic?               | PCB's are toxic subtance which is synthesize by industries, it used to make the paint black. Nowadays it's forbidden in Europe but it still to influence the marin's life like porpoise. The female porpoise are infected by PCB then it suckle its calves and the calves are infected by PCB too. But PCB make big dommages at the brain of the porpoise calves.  |
| Procedure/what was examinated? | They analysed the PCB and its effects in some familly of ceatacean. Its effect on the developpement of the young whales. They tried to monitor the PCB concentration in the sea. They analysed the effect on the porpoise to saw the effect on species who are in extintion like orcas.   |
| Conclusions/discovery?       | First the scientits found that there are 209 type of PCB and all that type make a neurotoxic cocktail. They found that the PCB are dangerous for the developement of the brain of porpoise calves. PCBs are in the milk of the whales and they pass it to the calves but not also. If an animal have PCB in it its predator will eat it and have the PCB. So in the food chain the main predator will have a lot of PCB. They tried to monitor the PCB but it's impossible because there are a lot of mixing of PCBs and every PCB are different.  |
| Remaining questions?         | They don't know all effects of the PCB on the marin's life neither how stop this.   |



